jobs:
- name: go-image
  serial: true
  public: true
  plan:
  - aggregate:
    - get: images-resource
      trigger: false
      passed: [git-image]
    - get: base-image
      params: {save: true}
      trigger: false
  - put: go-resource-image
    params:
      load_base: base-image
      build: images-resource/ci/golang1.6
    get_params: {rootfs: true}

- name: go-image1.7
  serial: true
  public: true
  plan:
  - aggregate:
    - get: images-resource
      trigger: false
      passed: [git-image]
    - get: base-image
      params: {save: true}
      trigger: false
  - put: go-resource-image17
    params:
      load_base: base-image
      build: images-resource/ci/golang1.7
    get_params: {rootfs: true}

- name: ruby-image
  serial: true
  public: true
  plan:
  - aggregate:
    - get: images-resource
      trigger: false
    - get: base-image
      params: {save: true}
      trigger: false
  - put: ruby-resource-image
    params:
      load_base: base-image
      build: images-resource/ci/ruby2.2.3
    get_params: {rootfs: true}

- name: ruby-image2.3.1
  serial: true
  public: true
  plan:
  - aggregate:
    - get: images-resource
      trigger: false
    - get: base-image
      params: {save: true}
      trigger: false
  - put: ruby-resource-image2.3.1
    params:
      load_base: base-image
      build: images-resource/ci/ruby2.3.1
    get_params: {rootfs: true}

- name: git-image
  serial: true
  public: true
  plan:
  - aggregate:
    - get: images-resource
      trigger: false
    - get: base-image
      params: {save: true}
      trigger: false
  - put: git-resource-image
    params:
      load_base: base-image
      build: images-resource/ci/git2.4
    get_params: {rootfs: true}

- name: git-image2.10
  serial: true
  public: true
  plan:
  - aggregate:
    - get: images-resource
      trigger: false
    - get: base-image
      params: {save: true}
      trigger: false
  - put: git-resource-image2.10
    params:
      load_base: base-image
      build: images-resource/ci/git2.10
    get_params: {rootfs: true}

- name: git-image2.8.4
  serial: true
  public: true
  plan:
  - aggregate:
    - get: images-resource
      trigger: false
    - get: base-image
      params: {save: true}
      trigger: false
  - put: git-resource-image2.8.4
    params:
      load_base: base-image
      build: images-resource/ci/git2.8.4
    get_params: {rootfs: true}

resources:
- name: images-resource
  type: git
  source:
    uri: https://github.com/barthy1/ppc64le_images.git
    branch: master
- name: base-image
  type: docker-image
  source:
    repository: ppc64le/ubuntu
    tag: "14.04"

- name: go-resource-image
  type: docker-image
  source:
    repository: 140.211.168.97:5000/golang
    tag: 1.6
    insecure_registries: ["140.211.168.97:5000"]
    username: {{username}}
    password: {{password}}

- name: go-resource-image17
  type: docker-image
  source:
    repository: 140.211.168.97:5000/golang
    tag: "1.7"
    insecure_registries: ["140.211.168.97:5000"]
    username: {{username}}
    password: {{password}}

- name: git-resource-image
  type: docker-image
  source:
    repository: 140.211.168.97:5000/git
    tag: 2.4
    insecure_registries: ["140.211.168.97:5000"]
    username: {{username}}
    password: {{password}}
- name: git-resource-image2.10
  type: docker-image
  source:
    repository: 140.211.168.97:5000/git
    tag: 2.10.0
    insecure_registries: ["140.211.168.97:5000"]
    username: {{username}}
    password: {{password}}
- name: git-resource-image2.8.4
  type: docker-image
  source:
    repository: 140.211.168.97:5000/git
    tag: "2.8.4"
    insecure_registries: ["140.211.168.97:5000"]
    username: {{username}}
    password: {{password}}
- name: ruby-resource-image
  type: docker-image
  source:
    repository: 140.211.168.97:5000/ruby
    insecure_registries: ["140.211.168.97:5000"]
    username: {{username}}
    password: {{password}}
    tag: "2.2.3"
- name: ruby-resource-image2.3.1
  type: docker-image
  source:
    repository: 140.211.168.97:5000/ruby
    insecure_registries: ["140.211.168.97:5000"]
    username: {{username}}
    password: {{password}}
    tag: "2.3.1"
resource_types:
#- name: git
#  type: docker-image
#  source:
#    repository: 140.211.168.97:5000/git-resource-new
#    insecure_registries: ["140.211.168.97:5000"]
#    username: {{username}}
#    password: {{password}}

#- name: docker-image
#  type: docker-image
#  source:
#    repository: 140.211.168.97:5000/docker-image-resource-new-1
#    insecure_registries: ["140.211.168.97:5000"]
#    username: {{username}}
#    password: {{password}}
